version: '3.1'

networks:
  wlc-network:

services:
  app:
    image: wlc-app
    container_name: wlc
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - '8080:8080'
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    networks:
      - wlc-network

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./db_data/:/data/db
      - /etc/timezone:/etc/timezone:ro
    networks:
      - wlc-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express-wlc
    depends_on:
      - mongo
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - wlc-network
