version: '3.4'

networks:
  grafana:
  wlc-external:
        name: wlc-app_wlc-network
        external: true
  wmc-external:
        name: wmc-app_wmc-network
        external: true

services:
  grafana:
      image: grafana/grafana:11.0.0
      container_name: grafana
      ports:
        - "4000:3000"
      volumes:
        - grafana-storage:/var/lib/grafana
        - ./dashboards:/etc/grafana/provisioning/dashboards
        # - ./datasources:/etc/grafana/provisioning/datasources
      networks:
        - grafana

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: -config.file=/etc/tempo.yml
    volumes:
      - ./tempo-config.yml:/etc/tempo.yml
      # - ./tempo-data:/tmp/tempo
      - tempo-storage:/tmp/tempo
    ports:
      - "3200:3200"   # Tempo UI
      - "4318:4318"   # OTLP HTTP receiver
    networks:
      - grafana
      - wlc-external
      - wmc-external

volumes:
  grafana-storage: {}
  tempo-storage: {}