version: "3.4"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - grafana-external
      - wlc-external
      - wmc-external


networks:
  grafana-external:
    name: grafana_grafana
    external: true
  wlc-external:
    name: wlc-app_wlc-network
    external: true
  wmc-external:
    name: wmc-app_wmc-network
    external: true